name: WakaTime Readme

on:
  schedule:
    - cron: "0 0 * * *" # tous les jours à minuit UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Mise à jour du temps de code WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_EDITORS: true
